name: testing building LaTeX documents
on:
  workflow_dispatch:
  push:
    paths:
      - '**.tex'

jobs:

  pdf-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: ./
          root_file: ./main.tex
