name: testing the docker image work
on:
  workflow_dispatch:
  push:

jobs:

  pdf-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: docker image build
        run: |
          docker build . -t latexbuild
      - name: latex to pdf
        run: |
          docker run --rm -v `pwd`:/workspace/ latexbuild bash -c 'latexmk main.tex -xelatex -synctex=1'
          docker run --rm -v `pwd`:/workspace/ latexbuild bash -c 'latexmk thesis.tex -xelatex -synctex=1'
      - name: Check if the pdf exists
        run: |
          [[ -f main.pdf ]] || echo 'No file'
          [[ -f thesis.pdf ]] || echo 'No file'
