name: Release template
on:
  workflow_dispatch:
  release:


jobs:

  pdf-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: ./
          root_file: ./main.tex
          latexmk_use_xelatex: true
      - name: Uploads release
        uses: actions/upload-artifact@v2
        with:
          name: template
          path: ./main.pdf
